<?php

return [
    'url' => env('THERMAL_PRINTER_SERVER_URL', 'YOUR_THERMAL_PRINTER_SERVER_URL'),
    'port' => env('THERMAL_PRINTER_SERVER_PORT', 'YOUR_THERMAL_PRINTER_SERVER_PORT'),
    'token' => env('THERMAL_PRINTER_SERVER_TOKEN', 'YOUR_THERMAL_PRINTER_SERVER_TOKEN'),
];